branches:
  only:
  - master
  - develop
langauge: node_js
node_js:
- 12.16.1
install:
- npm install
- lerna bootstrap --hoist
script:
- npm run build
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: covid-tutoring
  env: covid-tutoring-dev
  bucket_name: covid-tutoring
  access_key_id:
    secure: rYDvrHkxOHa0M8u0APuD1+17pOeZlwa8+4eJ8AK7kdDS/xUjMK/TRUUrLO298fkd7ImlD5E2bQmfMHNwh/OfEMx8/kgkFP4XoSGFy8wkqNhMrt5A/6VNiioQ39lraDrscZ85JljlXVSQxpgwFbSHVUfQnB/vi2HfTY/LIEU0YDDtP9Tx3QEdnVkUHgG6QI7PDIpakvgO8l0CYkBLJq2woxO/5PY6tbigiCy1cACWPadZriMKgxmlX8NnMs8KtZiFu7JAwnglsHUzockg31lFu1puAVCTGR57IEgcSt/u0439j+FoS23gx2BUA4sazKRsBT6j6J7c1nVj64caOLy1CUqG3A3LMyTGpc8OUSUje2Us2EHnOqI6oIuYqLGOGVvVr9A0ISVjeGizUlJuMNvB+8mshb6zjMzQIGciOAkofvJCWa84Q543gOGMdKvs5b74fu9iQlqzeeoTrmXxQ9Wp2hOCiwbzZNDTo7mhD7OqCdcAUBE6GQr3azwdWjmOGix2jry5MlIO68JyKf90VofSGywms5tlE0FI8eDgqfr2CKFGMQYKYqxKENqfWg3Cw/RHFIw/neM0kTMiYgs/S7QiQY4c+cDwwyJBpJdx3lZYB4FrMVmE6hIeaMbWYUi2u/NTw9llrrcNgOV89OVwPHUeZ+akkRmMV70Y+NOhmO001HI=
  secret_access_key:
    secure: UNXC0AXEZamzNmDsSO3JpvuwI7gjo7FIZ3PvZ2kyLyrD6RdGaALltpjLpL7teiCA63Q2Cd9Prd/HWkMG/FjeqoxiTazk1xZiQHLXwxzXQCogAc+i2a3IjBiw/WEr9fz4DoMWipgh33TZ3fMcos8cuiv3+mWRiR7cFis/s8Zln26U11DgmpgJzTPGgDi6dwWTL7xS8z/epP96Wha/eLRlYFYoFgGo+oSpZe2lqAvg0kcXgS/mXMOBBpbVYC947hArTHgezlYDcq2+gQKVa823aGqvDYU5Y+MGkMExngtY81xQlWiZXifDXJln6SNT3/DtQxoUIRStcbYR73Zt2mtIKwwewFg+w9z3IaYJV50g2cwj8kw66zGbpiwnzRmJSNVQT1p8Fr66ynn6lYFMxMIiM77QbykfocUoJSGbioKk4KHCfcpM0PAyulXtBO5JSBGLccM8nYZ0R6rUEQWjBmKolEckW0jXWjhpDxuQYoJ20hcgQjVnVXYSk8WnxV5nNfIUM2diBlISADFTaCstjkhON0p9lVea/enz/WcaWErchmoWWwTdFTntka9jAy3NNHzVQV6fmVOTvFgpdkJsWvOgut0veuhqfZ099SgLMjoBG8/JC9PnVLxEkpsFCwAQvOEolxAKYbiF+6VmnC2ZFsjgjd18U9xLpPjOlZ28LXBQGAc=
