os: linux
dist: focal

language: node_js
node_js: 12.18.3

addons:
  apt:
    packages:
      - libgconf-2.4 # Required by Cypress
  chrome: stable
  firefox: latest

cache:
  directories:
    - $HOME/.cache/Cypress
    - $HOME/.cache/firebase/emulators
    - $HOME/.cache/yarn
    - .next/cache

env:
  global:
    - NODE_ENV=test
    - PERCY_PARALLEL_NONCE=$TRAVIS_BUILD_ID
    - PERCY_PARALLEL_TOTAL=9
  jobs:
    - BROWSER=electron PARALLEL=1
    - BROWSER=electron PARALLEL=2
    - BROWSER=electron PARALLEL=3
    - BROWSER=firefox PARALLEL=1
    - BROWSER=firefox PARALLEL=2
    - BROWSER=firefox PARALLEL=3
    - BROWSER=chrome PARALLEL=1
    - BROWSER=chrome PARALLEL=2
    - BROWSER=chrome PARALLEL=3

jobs:
  fast_finish: true
  allow_failures:
    - env: BROWSER=firefox PARALLEL=1
    - env: BROWSER=firefox PARALLEL=2
    - env: BROWSER=firefox PARALLEL=3
    - env: BROWSER=chrome PARALLEL=1
    - env: BROWSER=chrome PARALLEL=2
    - env: BROWSER=chrome PARALLEL=3

install:
  - yarn install --immutable --immutable-cache

before_script:
  - yarn start:db & yarn wait-on http-get://localhost:8080
  - yarn build

script:
  - yarn start:next &>/dev/null & yarn wait-on http://localhost:3000
  - yarn start:cy --record --parallel --headless --group $BROWSER -b $BROWSER

after_script:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack:
    secure: VPQHtQbKY9D/RgtO+i5+PADiXUIdjXv/xdAq656SU9c2VodrUkNBT0MCfyoY4U/RzzLIwASxGSPFe+zxCpjigrrDoRePG05VUt3NwecX3KYaKywNzV62OGdNAZ49WydOaW/ADNdtducRn9ou2jPrgVM+5p63DHu2Nx1w5G79x1A9fn4WgZW9neIL2eYgevxozB8PlQLOI40bz7xcP1fOAwHftPP+KgOof8lJdmHIodRY+jwVdojL708rkNWZf/WsvijK+Qa/EUtZ2Z/Tr+WJAcPOXdI2wyrSxROhSJOWKD+AaPXsXP/0SfCBZ9ZVU6Qc16T4nnQsVfpssxSh0f6ldSFfqGXi5BP7pg6r9PuD+8Pj3aM4Vz/ZCJYT83v3jxBbsZKFG9vKrWdarc01mfV8zzZzNMEdjqcTaLLVWMUIzPvvqd24FYo7UA/PI/NE7KjumYJy6VdHzY3jghJXoZQy6+6Jjoo8fj0QHBVPnsKY1fzCwZP+KUL5Lb1irQQP3E8WAf4WKLOo8qKoKIljOKyfURrhqOJL9+z6MVBfirnxnY9x4Xf0aQ/gDJP2qrZtbC5RXrF8lwypDY8EdcyOfCFNBcl/+hsdVOR9pTMlqaeo70tYBPU779Zq/pSzpc+BVXKiqSp+lc517eJdPyivjWr5+q7Cpz9u+F+7pWMF9AP0IrI=
